name: CI
on:
  pull_request:
    branches: [develop]
  push:
    branches: [develop]  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use nodeJS
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm ci
      - run: npm run format:check
      - run: npm test -- --coverage
        env:
          CI: true
      - name: Build Project
        if: github.context.event-name == 'push'
        run: npm run build    
      - run: npm install -g surge
      - name: Deploy to Staging
        if: github.context.event-name == 'push'
        run: npx surge --project ./build --domain totof44.surge.sh
        env:
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
